### PR TITLE
Implement setHiddenCountLabel for ABClusterAnnotationView

### PR DESCRIPTION
**Pull request by spbvasilenko**
Implement setHiddenCountLabel for ABClusterAnnotationView, if we setting annotationView.image = someImage...

### CODE REVIEW

**Comment by bigfish24** [comment]
@spbvasilenko thanks for doing this! Looking at your commit, I realized maybe it is best to just make the countLabel a public readonly property. This way someone could tweak the text font, color, or make it hidden directly.

Thoughts?

**Comment by spbvasilenko** [comment]
@bigfish24 yup, idea to make the countLabel a public property as well

**Comment by bigfish24** [comment]
Ok, I committed the change to make the countLabel public: https://github.com/bigfish24/ABFRealmMapView/commit/a34bfef6e47aeb6edb9fb55821237b6d582386ee

I will create a new Cocoapods release with this.

**Comment by spbvasilenko** [comment]
Great! Thanks!

**Pull request closed without merging**
