### PR TITLE
2.0 iOS Framework

### PR DESCRIPTION
**Pull request by ataibarkai**
I’ve refactored the project to support frameworks (the project is now simply an iOS framework), along with Carthage.

A few notes:

CocoaPods support is tanked, but should be pretty easy to regain.
Deployment target is now 8.0, the lowest supported by iOS dynamic frameworks.

I’ve also converted RBQFetchedResultsController (will send a separate PR) and have tested that both work using Carthage.

### CODE REVIEW

**Comment by ataibarkai** [comment]
Woops, I had incorrectly thought you were also behind RBQFetchedResultsController.

In order to convert this project to being a simple iOS Framework I had to convert RBQFetchedResultsController likewise.

There is a subtlety in the case of RBQFetchedResultsController, though (you can check out the PR on that project) so they may not accept the PR right away.

May affect you accepting this PR too...

**Comment by bigfish24** [comment]
I am the same guy behind both. RBQFRC was just built for my company Roobiq hence why it lives there.

**Comment by ataibarkai** [comment]
Great, that should make resolving all the hiccups easier.

**Comment by ataibarkai** [comment]
I've updated this to use the latest RBQFetchedResultsController.

There is one minor backwards-compatibility issue: the project/module is now called RealmMapViewFramework rather than RealmMapView.
It's because of a name-conflict issue / possible Swift bug. Check out the comments on the dde08a0 commit.

CocoaPods support is still needed, I'd appreciate if you could handle that end because I've never done that. Shouldn't be any different from usual.

Let me know if I can help somehow.

**Comment by bigfish24** [comment]
I am confused on why Cocoapods is broken... can you explain why the previous setup with Cocoapods won't work with your changes?

**Comment by bigfish24** [comment]
Closed in exchange for: https://github.com/bigfish24/ABFRealmMapView/commit/4cc389f9d4e5a5545e0071f04547e8f17eeb2dd2

**Pull request closed without merging**
